service: challenge2022

frameworkVersion: '2 || 3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  environment: ${file(./.env.json)}
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: ./src/useCases/helloWorld/index.handler
    events:
      - http:
          path: /
          method: get
          cors: true  
          # authorizer:
          #   type: JWT
          #   functionName: authorizerFunction
          
  authorizerFunction:
    handler: ./src/auth/authorizer.authorizerFun